# ===== MySQL Database Configuration =====
db.driver=com.mysql.cj.jdbc.Driver
db.url=${REMOTE_DB_URL}
db.username=${REMOTE_DB_USER}
db.password=${REMOTE_DB_PW}

# ===== local DB =====
# db.url=jdbc:mysql://localhost:3306/sanai?...
# db.username=
# db.password=

# ===== Connection Pool Settings =====
db.initialSize=5
db.maxActive=10
db.maxIdle=5
db.minIdle=2