# JWT \uC2DC\uD06C\uB9BF \uD0A4 \uC124\uC815
jwt.secret=${JWT_SECRET_KEY}

# Access Token \uC720\uD6A8 \uC2DC\uAC04: 30\uBD84
jwt.access-token-validity=1800000

# Refresh Token \uC720\uD6A8 \uC2DC\uAC04: 7\uC77C
jwt.refresh-token-validity=604800000